linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - goconst
    - gocyclo
    - unused
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 15

run:
  timeout: 5m
