// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bank_connections.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteBankConnection = `-- name: DeleteBankConnection :execresult
DELETE FROM bank_connections WHERE id = $1 AND user_id = $2
`

type DeleteBankConnectionParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteBankConnection(ctx context.Context, arg DeleteBankConnectionParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteBankConnection, arg.ID, arg.UserID)
}

const getBankConnectionByID = `-- name: GetBankConnectionByID :one
SELECT id, user_id, institution_id, institution_name, session_id, status, auth_expires_at, created_at, updated_at
FROM bank_connections
WHERE id = $1
`

func (q *Queries) GetBankConnectionByID(ctx context.Context, id int64) (BankConnection, error) {
	row := q.db.QueryRow(ctx, getBankConnectionByID, id)
	var i BankConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstitutionID,
		&i.InstitutionName,
		&i.SessionID,
		&i.Status,
		&i.AuthExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBankConnection = `-- name: InsertBankConnection :one
INSERT INTO bank_connections (user_id, institution_id, institution_name, session_id, status, auth_expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, institution_id, institution_name, session_id, status, auth_expires_at, created_at, updated_at
`

type InsertBankConnectionParams struct {
	UserID          int64              `json:"user_id"`
	InstitutionID   string             `json:"institution_id"`
	InstitutionName string             `json:"institution_name"`
	SessionID       string             `json:"session_id"`
	Status          string             `json:"status"`
	AuthExpiresAt   pgtype.Timestamptz `json:"auth_expires_at"`
}

func (q *Queries) InsertBankConnection(ctx context.Context, arg InsertBankConnectionParams) (BankConnection, error) {
	row := q.db.QueryRow(ctx, insertBankConnection,
		arg.UserID,
		arg.InstitutionID,
		arg.InstitutionName,
		arg.SessionID,
		arg.Status,
		arg.AuthExpiresAt,
	)
	var i BankConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstitutionID,
		&i.InstitutionName,
		&i.SessionID,
		&i.Status,
		&i.AuthExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveBankConnections = `-- name: ListActiveBankConnections :many
SELECT id, user_id, institution_id, institution_name, session_id, status, auth_expires_at, created_at, updated_at
FROM bank_connections
WHERE status = 'active' AND auth_expires_at > NOW()
`

func (q *Queries) ListActiveBankConnections(ctx context.Context) ([]BankConnection, error) {
	rows, err := q.db.Query(ctx, listActiveBankConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BankConnection{}
	for rows.Next() {
		var i BankConnection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InstitutionID,
			&i.InstitutionName,
			&i.SessionID,
			&i.Status,
			&i.AuthExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankConnectionsByUser = `-- name: ListBankConnectionsByUser :many
SELECT id, user_id, institution_id, institution_name, session_id, status, auth_expires_at, created_at, updated_at
FROM bank_connections
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBankConnectionsByUser(ctx context.Context, userID int64) ([]BankConnection, error) {
	rows, err := q.db.Query(ctx, listBankConnectionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BankConnection{}
	for rows.Next() {
		var i BankConnection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InstitutionID,
			&i.InstitutionName,
			&i.SessionID,
			&i.Status,
			&i.AuthExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBankConnectionSession = `-- name: UpdateBankConnectionSession :exec
UPDATE bank_connections
SET session_id = $2, status = $3, auth_expires_at = $4, updated_at = NOW()
WHERE id = $1
`

type UpdateBankConnectionSessionParams struct {
	ID            int64              `json:"id"`
	SessionID     string             `json:"session_id"`
	Status        string             `json:"status"`
	AuthExpiresAt pgtype.Timestamptz `json:"auth_expires_at"`
}

func (q *Queries) UpdateBankConnectionSession(ctx context.Context, arg UpdateBankConnectionSessionParams) error {
	_, err := q.db.Exec(ctx, updateBankConnectionSession,
		arg.ID,
		arg.SessionID,
		arg.Status,
		arg.AuthExpiresAt,
	)
	return err
}

const updateBankConnectionStatus = `-- name: UpdateBankConnectionStatus :exec
UPDATE bank_connections SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateBankConnectionStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateBankConnectionStatus(ctx context.Context, arg UpdateBankConnectionStatusParams) error {
	_, err := q.db.Exec(ctx, updateBankConnectionStatus, arg.ID, arg.Status)
	return err
}
