// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bank_accounts.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const getBankAccountByIBANAndCurrencyForUser = `-- name: GetBankAccountByIBANAndCurrencyForUser :one
SELECT ba.id, ba.bank_connection_id, ba.external_id, ba.iban, ba.currency, ba.name, ba.last_synced_at, ba.created_at, ba.updated_at, ba.custom_name
FROM bank_accounts ba
JOIN bank_connections bc ON bc.id = ba.bank_connection_id
WHERE ba.iban = $1 AND ba.currency = $2 AND bc.user_id = $3
LIMIT 1
`

type GetBankAccountByIBANAndCurrencyForUserParams struct {
	Iban     pgtype.Text `json:"iban"`
	Currency string      `json:"currency"`
	UserID   int64       `json:"user_id"`
}

func (q *Queries) GetBankAccountByIBANAndCurrencyForUser(ctx context.Context, arg GetBankAccountByIBANAndCurrencyForUserParams) (BankAccount, error) {
	row := q.db.QueryRow(ctx, getBankAccountByIBANAndCurrencyForUser, arg.Iban, arg.Currency, arg.UserID)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.BankConnectionID,
		&i.ExternalID,
		&i.Iban,
		&i.Currency,
		&i.Name,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomName,
	)
	return i, err
}

const getBankAccountByID = `-- name: GetBankAccountByID :one
SELECT id, bank_connection_id, external_id, iban, currency, name, last_synced_at, created_at, updated_at, custom_name
FROM bank_accounts
WHERE id = $1
`

func (q *Queries) GetBankAccountByID(ctx context.Context, id int64) (BankAccount, error) {
	row := q.db.QueryRow(ctx, getBankAccountByID, id)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.BankConnectionID,
		&i.ExternalID,
		&i.Iban,
		&i.Currency,
		&i.Name,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomName,
	)
	return i, err
}

const insertBankAccount = `-- name: InsertBankAccount :one
INSERT INTO bank_accounts (bank_connection_id, external_id, iban, currency, name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, bank_connection_id, external_id, iban, currency, name, last_synced_at, created_at, updated_at, custom_name
`

type InsertBankAccountParams struct {
	BankConnectionID int64       `json:"bank_connection_id"`
	ExternalID       string      `json:"external_id"`
	Iban             pgtype.Text `json:"iban"`
	Currency         string      `json:"currency"`
	Name             string      `json:"name"`
}

func (q *Queries) InsertBankAccount(ctx context.Context, arg InsertBankAccountParams) (BankAccount, error) {
	row := q.db.QueryRow(ctx, insertBankAccount,
		arg.BankConnectionID,
		arg.ExternalID,
		arg.Iban,
		arg.Currency,
		arg.Name,
	)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.BankConnectionID,
		&i.ExternalID,
		&i.Iban,
		&i.Currency,
		&i.Name,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomName,
	)
	return i, err
}

const linkBankAccountToWorkspace = `-- name: LinkBankAccountToWorkspace :exec
INSERT INTO workspace_bank_accounts (workspace_id, bank_account_id)
VALUES ($1, $2)
ON CONFLICT (workspace_id, bank_account_id) DO NOTHING
`

type LinkBankAccountToWorkspaceParams struct {
	WorkspaceID   int64 `json:"workspace_id"`
	BankAccountID int64 `json:"bank_account_id"`
}

func (q *Queries) LinkBankAccountToWorkspace(ctx context.Context, arg LinkBankAccountToWorkspaceParams) error {
	_, err := q.db.Exec(ctx, linkBankAccountToWorkspace, arg.WorkspaceID, arg.BankAccountID)
	return err
}

const listBankAccountsByConnection = `-- name: ListBankAccountsByConnection :many
SELECT id, bank_connection_id, external_id, iban, currency, name, last_synced_at, created_at, updated_at, custom_name
FROM bank_accounts
WHERE bank_connection_id = $1
ORDER BY created_at
`

func (q *Queries) ListBankAccountsByConnection(ctx context.Context, bankConnectionID int64) ([]BankAccount, error) {
	rows, err := q.db.Query(ctx, listBankAccountsByConnection, bankConnectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BankAccount{}
	for rows.Next() {
		var i BankAccount
		if err := rows.Scan(
			&i.ID,
			&i.BankConnectionID,
			&i.ExternalID,
			&i.Iban,
			&i.Currency,
			&i.Name,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankAccountsByUser = `-- name: ListBankAccountsByUser :many
SELECT ba.id, ba.bank_connection_id, ba.external_id, ba.iban, ba.currency, ba.name, ba.last_synced_at, ba.created_at, ba.updated_at, ba.custom_name,
       bc.institution_name
FROM bank_accounts ba
JOIN bank_connections bc ON bc.id = ba.bank_connection_id
WHERE bc.user_id = $1
ORDER BY bc.institution_name, ba.name
`

type ListBankAccountsByUserRow struct {
	ID               int64              `json:"id"`
	BankConnectionID int64              `json:"bank_connection_id"`
	ExternalID       string             `json:"external_id"`
	Iban             pgtype.Text        `json:"iban"`
	Currency         string             `json:"currency"`
	Name             string             `json:"name"`
	LastSyncedAt     pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CustomName       string             `json:"custom_name"`
	InstitutionName  string             `json:"institution_name"`
}

func (q *Queries) ListBankAccountsByUser(ctx context.Context, userID int64) ([]ListBankAccountsByUserRow, error) {
	rows, err := q.db.Query(ctx, listBankAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBankAccountsByUserRow{}
	for rows.Next() {
		var i ListBankAccountsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.BankConnectionID,
			&i.ExternalID,
			&i.Iban,
			&i.Currency,
			&i.Name,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomName,
			&i.InstitutionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankAccountsByWorkspace = `-- name: ListBankAccountsByWorkspace :many
SELECT ba.id, ba.bank_connection_id, ba.external_id, ba.iban, ba.currency, ba.name, ba.last_synced_at, ba.created_at, ba.updated_at, ba.custom_name,
       bc.institution_name
FROM bank_accounts ba
JOIN workspace_bank_accounts wba ON wba.bank_account_id = ba.id
JOIN bank_connections bc ON bc.id = ba.bank_connection_id
WHERE wba.workspace_id = $1
ORDER BY bc.institution_name, ba.name
`

type ListBankAccountsByWorkspaceRow struct {
	ID               int64              `json:"id"`
	BankConnectionID int64              `json:"bank_connection_id"`
	ExternalID       string             `json:"external_id"`
	Iban             pgtype.Text        `json:"iban"`
	Currency         string             `json:"currency"`
	Name             string             `json:"name"`
	LastSyncedAt     pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CustomName       string             `json:"custom_name"`
	InstitutionName  string             `json:"institution_name"`
}

func (q *Queries) ListBankAccountsByWorkspace(ctx context.Context, workspaceID int64) ([]ListBankAccountsByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listBankAccountsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBankAccountsByWorkspaceRow{}
	for rows.Next() {
		var i ListBankAccountsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.BankConnectionID,
			&i.ExternalID,
			&i.Iban,
			&i.Currency,
			&i.Name,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomName,
			&i.InstitutionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByBankAccount = `-- name: ListWorkspacesByBankAccount :many
SELECT workspace_id FROM workspace_bank_accounts WHERE bank_account_id = $1
`

func (q *Queries) ListWorkspacesByBankAccount(ctx context.Context, bankAccountID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByBankAccount, bankAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var workspace_id int64
		if err := rows.Scan(&workspace_id); err != nil {
			return nil, err
		}
		items = append(items, workspace_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkBankAccountFromWorkspace = `-- name: UnlinkBankAccountFromWorkspace :execresult
DELETE FROM workspace_bank_accounts WHERE workspace_id = $1 AND bank_account_id = $2
`

type UnlinkBankAccountFromWorkspaceParams struct {
	WorkspaceID   int64 `json:"workspace_id"`
	BankAccountID int64 `json:"bank_account_id"`
}

func (q *Queries) UnlinkBankAccountFromWorkspace(ctx context.Context, arg UnlinkBankAccountFromWorkspaceParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, unlinkBankAccountFromWorkspace, arg.WorkspaceID, arg.BankAccountID)
}

const updateBankAccountConnection = `-- name: UpdateBankAccountConnection :exec
UPDATE bank_accounts
SET external_id = $2, bank_connection_id = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateBankAccountConnectionParams struct {
	ID               int64  `json:"id"`
	ExternalID       string `json:"external_id"`
	BankConnectionID int64  `json:"bank_connection_id"`
}

func (q *Queries) UpdateBankAccountConnection(ctx context.Context, arg UpdateBankAccountConnectionParams) error {
	_, err := q.db.Exec(ctx, updateBankAccountConnection, arg.ID, arg.ExternalID, arg.BankConnectionID)
	return err
}

const updateBankAccountCustomName = `-- name: UpdateBankAccountCustomName :one
UPDATE bank_accounts SET custom_name = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, bank_connection_id, external_id, iban, currency, name, last_synced_at, created_at, updated_at, custom_name
`

type UpdateBankAccountCustomNameParams struct {
	ID         int64  `json:"id"`
	CustomName string `json:"custom_name"`
}

func (q *Queries) UpdateBankAccountCustomName(ctx context.Context, arg UpdateBankAccountCustomNameParams) (BankAccount, error) {
	row := q.db.QueryRow(ctx, updateBankAccountCustomName, arg.ID, arg.CustomName)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.BankConnectionID,
		&i.ExternalID,
		&i.Iban,
		&i.Currency,
		&i.Name,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomName,
	)
	return i, err
}

const updateBankAccountLastSyncedAt = `-- name: UpdateBankAccountLastSyncedAt :exec
UPDATE bank_accounts SET last_synced_at = $2, updated_at = NOW() WHERE id = $1
`

type UpdateBankAccountLastSyncedAtParams struct {
	ID           int64              `json:"id"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
}

func (q *Queries) UpdateBankAccountLastSyncedAt(ctx context.Context, arg UpdateBankAccountLastSyncedAtParams) error {
	_, err := q.db.Exec(ctx, updateBankAccountLastSyncedAt, arg.ID, arg.LastSyncedAt)
	return err
}
