// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, workspace_id, name, icon, slug, created_at, updated_at
FROM categories
WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Icon,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, workspace_id, name, icon, slug, created_at, updated_at
FROM categories
WHERE workspace_id = $1 AND name = $2
`

type GetCategoryByNameParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	Name        string `json:"name"`
}

func (q *Queries) GetCategoryByName(ctx context.Context, arg GetCategoryByNameParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByName, arg.WorkspaceID, arg.Name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Icon,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, workspace_id, name, icon, slug, created_at, updated_at
FROM categories
WHERE workspace_id = $1 AND slug = $2
`

type GetCategoryBySlugParams struct {
	WorkspaceID int64       `json:"workspace_id"`
	Slug        pgtype.Text `json:"slug"`
}

func (q *Queries) GetCategoryBySlug(ctx context.Context, arg GetCategoryBySlugParams) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, arg.WorkspaceID, arg.Slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Icon,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCategory = `-- name: InsertCategory :one
INSERT INTO categories (workspace_id, name, icon, slug)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, name, icon, slug, created_at, updated_at
`

type InsertCategoryParams struct {
	WorkspaceID int64       `json:"workspace_id"`
	Name        string      `json:"name"`
	Icon        string      `json:"icon"`
	Slug        pgtype.Text `json:"slug"`
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, insertCategory,
		arg.WorkspaceID,
		arg.Name,
		arg.Icon,
		arg.Slug,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Icon,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoriesByWorkspace = `-- name: ListCategoriesByWorkspace :many
SELECT id, workspace_id, name, icon, slug, created_at, updated_at
FROM categories
WHERE workspace_id = $1
ORDER BY name
`

func (q *Queries) ListCategoriesByWorkspace(ctx context.Context, workspaceID int64) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Icon,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name       = $2,
    icon       = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, workspace_id, name, icon, slug, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Icon string `json:"icon"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.ID, arg.Name, arg.Icon)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Icon,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
