// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const bulkUpdateFirstEntryCategory = `-- name: BulkUpdateFirstEntryCategory :execresult
UPDATE entries SET category_id = $1
WHERE id IN (
    SELECT DISTINCT ON (transaction_id) id
    FROM entries
    WHERE transaction_id = ANY($2::bigint[])
    ORDER BY transaction_id, id
)
`

type BulkUpdateFirstEntryCategoryParams struct {
	CategoryID int64   `json:"category_id"`
	Column2    []int64 `json:"column_2"`
}

func (q *Queries) BulkUpdateFirstEntryCategory(ctx context.Context, arg BulkUpdateFirstEntryCategoryParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, bulkUpdateFirstEntryCategory, arg.CategoryID, arg.Column2)
}

const deleteEntriesByTransaction = `-- name: DeleteEntriesByTransaction :exec
DELETE FROM entries WHERE transaction_id = $1
`

func (q *Queries) DeleteEntriesByTransaction(ctx context.Context, transactionID int64) error {
	_, err := q.db.Exec(ctx, deleteEntriesByTransaction, transactionID)
	return err
}

const insertEntry = `-- name: InsertEntry :one
INSERT INTO entries (transaction_id, category_id, participant_id, amount, currency, note)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, transaction_id, category_id, participant_id, amount, currency, note
`

type InsertEntryParams struct {
	TransactionID int64          `json:"transaction_id"`
	CategoryID    int64          `json:"category_id"`
	ParticipantID pgtype.Int8    `json:"participant_id"`
	Amount        pgtype.Numeric `json:"amount"`
	Currency      string         `json:"currency"`
	Note          string         `json:"note"`
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, insertEntry,
		arg.TransactionID,
		arg.CategoryID,
		arg.ParticipantID,
		arg.Amount,
		arg.Currency,
		arg.Note,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.CategoryID,
		&i.ParticipantID,
		&i.Amount,
		&i.Currency,
		&i.Note,
	)
	return i, err
}

const listEntriesByTransaction = `-- name: ListEntriesByTransaction :many
SELECT id, transaction_id, category_id, participant_id, amount, currency, note
FROM entries
WHERE transaction_id = $1
ORDER BY id
`

func (q *Queries) ListEntriesByTransaction(ctx context.Context, transactionID int64) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntriesByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.CategoryID,
			&i.ParticipantID,
			&i.Amount,
			&i.Currency,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesByTransactionIDs = `-- name: ListEntriesByTransactionIDs :many
SELECT id, transaction_id, category_id, participant_id, amount, currency, note
FROM entries
WHERE transaction_id = ANY($1::bigint[])
ORDER BY transaction_id, id
`

func (q *Queries) ListEntriesByTransactionIDs(ctx context.Context, dollar_1 []int64) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntriesByTransactionIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.CategoryID,
			&i.ParticipantID,
			&i.Amount,
			&i.Currency,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntryCategory = `-- name: UpdateEntryCategory :exec
UPDATE entries SET category_id = $2 WHERE id = $1
`

type UpdateEntryCategoryParams struct {
	ID         int64 `json:"id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) UpdateEntryCategory(ctx context.Context, arg UpdateEntryCategoryParams) error {
	_, err := q.db.Exec(ctx, updateEntryCategory, arg.ID, arg.CategoryID)
	return err
}
