// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fundings.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteFunding = `-- name: DeleteFunding :execresult
DELETE FROM fundings
WHERE id = $1 AND workspace_id = $2
`

type DeleteFundingParams struct {
	ID          int64 `json:"id"`
	WorkspaceID int64 `json:"workspace_id"`
}

func (q *Queries) DeleteFunding(ctx context.Context, arg DeleteFundingParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteFunding, arg.ID, arg.WorkspaceID)
}

const getCategoryBudgetsByWorkspace = `-- name: GetCategoryBudgetsByWorkspace :many
SELECT id, workspace_id, user_id, year_month, amount, currency, category_id, created_at, updated_at
FROM fundings
WHERE workspace_id = $1 AND year_month >= $2 AND year_month <= $3 AND category_id IS NOT NULL
ORDER BY category_id, year_month
`

type GetCategoryBudgetsByWorkspaceParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	YearMonth   string `json:"year_month"`
	YearMonth_2 string `json:"year_month_2"`
}

func (q *Queries) GetCategoryBudgetsByWorkspace(ctx context.Context, arg GetCategoryBudgetsByWorkspaceParams) ([]Funding, error) {
	rows, err := q.db.Query(ctx, getCategoryBudgetsByWorkspace, arg.WorkspaceID, arg.YearMonth, arg.YearMonth_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Funding{}
	for rows.Next() {
		var i Funding
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFundingsByWorkspaceAndUsers = `-- name: GetFundingsByWorkspaceAndUsers :many
SELECT id, workspace_id, user_id, year_month, amount, currency, category_id, created_at, updated_at
FROM fundings
WHERE workspace_id = $1 AND year_month >= $2 AND year_month <= $3
ORDER BY user_id, year_month
`

type GetFundingsByWorkspaceAndUsersParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	YearMonth   string `json:"year_month"`
	YearMonth_2 string `json:"year_month_2"`
}

func (q *Queries) GetFundingsByWorkspaceAndUsers(ctx context.Context, arg GetFundingsByWorkspaceAndUsersParams) ([]Funding, error) {
	rows, err := q.db.Query(ctx, getFundingsByWorkspaceAndUsers, arg.WorkspaceID, arg.YearMonth, arg.YearMonth_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Funding{}
	for rows.Next() {
		var i Funding
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverallBudgetByWorkspace = `-- name: GetOverallBudgetByWorkspace :many
SELECT id, workspace_id, user_id, year_month, amount, currency, category_id, created_at, updated_at
FROM fundings
WHERE workspace_id = $1 AND year_month >= $2 AND year_month <= $3 AND category_id IS NULL
ORDER BY year_month
`

type GetOverallBudgetByWorkspaceParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	YearMonth   string `json:"year_month"`
	YearMonth_2 string `json:"year_month_2"`
}

func (q *Queries) GetOverallBudgetByWorkspace(ctx context.Context, arg GetOverallBudgetByWorkspaceParams) ([]Funding, error) {
	rows, err := q.db.Query(ctx, getOverallBudgetByWorkspace, arg.WorkspaceID, arg.YearMonth, arg.YearMonth_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Funding{}
	for rows.Next() {
		var i Funding
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFundingsByWorkspace = `-- name: ListFundingsByWorkspace :many
SELECT id, workspace_id, user_id, year_month, amount, currency, category_id, created_at, updated_at
FROM fundings
WHERE workspace_id = $1 AND year_month >= $2 AND year_month <= $3
ORDER BY year_month, user_id
`

type ListFundingsByWorkspaceParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	YearMonth   string `json:"year_month"`
	YearMonth_2 string `json:"year_month_2"`
}

func (q *Queries) ListFundingsByWorkspace(ctx context.Context, arg ListFundingsByWorkspaceParams) ([]Funding, error) {
	rows, err := q.db.Query(ctx, listFundingsByWorkspace, arg.WorkspaceID, arg.YearMonth, arg.YearMonth_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Funding{}
	for rows.Next() {
		var i Funding
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.YearMonth,
			&i.Amount,
			&i.Currency,
			&i.CategoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFunding = `-- name: UpsertFunding :one
INSERT INTO fundings (workspace_id, user_id, year_month, amount, currency, category_id)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (workspace_id, user_id, year_month, COALESCE(category_id, 0))
DO UPDATE SET amount = EXCLUDED.amount, currency = EXCLUDED.currency, updated_at = NOW()
RETURNING id, workspace_id, user_id, year_month, amount, currency, category_id, created_at, updated_at
`

type UpsertFundingParams struct {
	WorkspaceID int64          `json:"workspace_id"`
	UserID      int64          `json:"user_id"`
	YearMonth   string         `json:"year_month"`
	Amount      pgtype.Numeric `json:"amount"`
	Currency    string         `json:"currency"`
	CategoryID  pgtype.Int8    `json:"category_id"`
}

func (q *Queries) UpsertFunding(ctx context.Context, arg UpsertFundingParams) (Funding, error) {
	row := q.db.QueryRow(ctx, upsertFunding,
		arg.WorkspaceID,
		arg.UserID,
		arg.YearMonth,
		arg.Amount,
		arg.Currency,
		arg.CategoryID,
	)
	var i Funding
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.YearMonth,
		&i.Amount,
		&i.Currency,
		&i.CategoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
