// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invites.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getInviteByCode = `-- name: GetInviteByCode :one
SELECT
    wi.id, wi.workspace_id, wi.code, wi.role, wi.created_by,
    wi.expires_at, wi.used_by, wi.used_at, wi.created_at,
    w.name AS workspace_name,
    u.display_name AS inviter_name
FROM workspace_invites wi
JOIN workspaces w ON w.id = wi.workspace_id
JOIN users u ON u.id = wi.created_by
WHERE wi.code = $1
`

type GetInviteByCodeRow struct {
	ID            int64              `json:"id"`
	WorkspaceID   int64              `json:"workspace_id"`
	Code          string             `json:"code"`
	Role          MemberRole         `json:"role"`
	CreatedBy     int64              `json:"created_by"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	UsedBy        pgtype.Int8        `json:"used_by"`
	UsedAt        pgtype.Timestamptz `json:"used_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	WorkspaceName string             `json:"workspace_name"`
	InviterName   string             `json:"inviter_name"`
}

func (q *Queries) GetInviteByCode(ctx context.Context, code string) (GetInviteByCodeRow, error) {
	row := q.db.QueryRow(ctx, getInviteByCode, code)
	var i GetInviteByCodeRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Code,
		&i.Role,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedBy,
		&i.UsedAt,
		&i.CreatedAt,
		&i.WorkspaceName,
		&i.InviterName,
	)
	return i, err
}

const insertInvite = `-- name: InsertInvite :one
INSERT INTO workspace_invites (workspace_id, code, role, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, code, role, created_by, expires_at, used_by, used_at, created_at
`

type InsertInviteParams struct {
	WorkspaceID int64              `json:"workspace_id"`
	Code        string             `json:"code"`
	Role        MemberRole         `json:"role"`
	CreatedBy   int64              `json:"created_by"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertInvite(ctx context.Context, arg InsertInviteParams) (WorkspaceInvite, error) {
	row := q.db.QueryRow(ctx, insertInvite,
		arg.WorkspaceID,
		arg.Code,
		arg.Role,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i WorkspaceInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Code,
		&i.Role,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedBy,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markInviteUsed = `-- name: MarkInviteUsed :exec
UPDATE workspace_invites
SET used_by = $2, used_at = NOW()
WHERE id = $1
`

type MarkInviteUsedParams struct {
	ID     int64       `json:"id"`
	UsedBy pgtype.Int8 `json:"used_by"`
}

func (q *Queries) MarkInviteUsed(ctx context.Context, arg MarkInviteUsedParams) error {
	_, err := q.db.Exec(ctx, markInviteUsed, arg.ID, arg.UsedBy)
	return err
}
