// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthProvider string

const (
	AuthProviderGoogle AuthProvider = "google"
	AuthProviderGithub AuthProvider = "github"
)

func (e *AuthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProvider(s)
	case string:
		*e = AuthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProvider: %T", src)
	}
	return nil
}

type NullAuthProvider struct {
	AuthProvider AuthProvider `json:"auth_provider"`
	Valid        bool         `json:"valid"` // Valid is true if AuthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProvider), nil
}

type MemberRole string

const (
	MemberRoleOwner  MemberRole = "owner"
	MemberRoleEditor MemberRole = "editor"
	MemberRoleViewer MemberRole = "viewer"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole `json:"member_role"`
	Valid      bool       `json:"valid"` // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type RuleScope string

const (
	RuleScopeSystem    RuleScope = "system"
	RuleScopeUser      RuleScope = "user"
	RuleScopeWorkspace RuleScope = "workspace"
)

func (e *RuleScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RuleScope(s)
	case string:
		*e = RuleScope(s)
	default:
		return fmt.Errorf("unsupported scan type for RuleScope: %T", src)
	}
	return nil
}

type NullRuleScope struct {
	RuleScope RuleScope `json:"rule_scope"`
	Valid     bool      `json:"valid"` // Valid is true if RuleScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRuleScope) Scan(value interface{}) error {
	if value == nil {
		ns.RuleScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RuleScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRuleScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RuleScope), nil
}

type TransactionSource string

const (
	TransactionSourceManual TransactionSource = "manual"
	TransactionSourceImport TransactionSource = "import"
	TransactionSourceBank   TransactionSource = "bank"
)

func (e *TransactionSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionSource(s)
	case string:
		*e = TransactionSource(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionSource: %T", src)
	}
	return nil
}

type NullTransactionSource struct {
	TransactionSource TransactionSource `json:"transaction_source"`
	Valid             bool              `json:"valid"` // Valid is true if TransactionSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionSource) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionSource), nil
}

type TransactionType string

const (
	TransactionTypeExpense  TransactionType = "expense"
	TransactionTypeIncome   TransactionType = "income"
	TransactionTypeTransfer TransactionType = "transfer"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType `json:"transaction_type"`
	Valid           bool            `json:"valid"` // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type BankAccount struct {
	ID               int64              `json:"id"`
	BankConnectionID int64              `json:"bank_connection_id"`
	ExternalID       string             `json:"external_id"`
	Iban             pgtype.Text        `json:"iban"`
	Currency         string             `json:"currency"`
	Name             string             `json:"name"`
	LastSyncedAt     pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CustomName       string             `json:"custom_name"`
}

type BankConnection struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"user_id"`
	InstitutionID   string             `json:"institution_id"`
	InstitutionName string             `json:"institution_name"`
	SessionID       string             `json:"session_id"`
	Status          string             `json:"status"`
	AuthExpiresAt   pgtype.Timestamptz `json:"auth_expires_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CategorizationRule struct {
	ID               int64              `json:"id"`
	Scope            RuleScope          `json:"scope"`
	OwnerID          pgtype.Int8        `json:"owner_id"`
	WorkspaceID      pgtype.Int8        `json:"workspace_id"`
	MatchPattern     string             `json:"match_pattern"`
	TargetCategoryID int64              `json:"target_category_id"`
	Priority         int32              `json:"priority"`
	Enabled          bool               `json:"enabled"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	AmountMin        pgtype.Numeric     `json:"amount_min"`
	AmountMax        pgtype.Numeric     `json:"amount_max"`
	BankAccountID    pgtype.Int8        `json:"bank_account_id"`
	CounterpartyIban pgtype.Text        `json:"counterparty_iban"`
}

type Category struct {
	ID          int64              `json:"id"`
	WorkspaceID int64              `json:"workspace_id"`
	Name        string             `json:"name"`
	Icon        string             `json:"icon"`
	Slug        pgtype.Text        `json:"slug"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Entry struct {
	ID            int64          `json:"id"`
	TransactionID int64          `json:"transaction_id"`
	CategoryID    int64          `json:"category_id"`
	ParticipantID pgtype.Int8    `json:"participant_id"`
	Amount        pgtype.Numeric `json:"amount"`
	Currency      string         `json:"currency"`
	Note          string         `json:"note"`
}

type Funding struct {
	ID          int64              `json:"id"`
	WorkspaceID int64              `json:"workspace_id"`
	UserID      int64              `json:"user_id"`
	YearMonth   string             `json:"year_month"`
	Amount      pgtype.Numeric     `json:"amount"`
	Currency    string             `json:"currency"`
	CategoryID  pgtype.Int8        `json:"category_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	ID               int64              `json:"id"`
	WorkspaceID      int64              `json:"workspace_id"`
	CreatedBy        int64              `json:"created_by"`
	TotalAmount      pgtype.Numeric     `json:"total_amount"`
	Currency         string             `json:"currency"`
	Description      string             `json:"description"`
	Date             pgtype.Date        `json:"date"`
	Fingerprint      pgtype.Text        `json:"fingerprint"`
	Source           TransactionSource  `json:"source"`
	TransactionType  TransactionType    `json:"transaction_type"`
	Notes            string             `json:"notes"`
	BankAccountID    pgtype.Int8        `json:"bank_account_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Iban             pgtype.Text        `json:"iban"`
	CounterpartyIban pgtype.Text        `json:"counterparty_iban"`
}

type User struct {
	ID                int64              `json:"id"`
	Email             string             `json:"email"`
	DisplayName       string             `json:"display_name"`
	AvatarUrl         string             `json:"avatar_url"`
	Provider          AuthProvider       `json:"provider"`
	ProviderID        string             `json:"provider_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	PreferredLanguage string             `json:"preferred_language"`
}

type Workspace struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	OwnerID     int64              `json:"owner_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceBankAccount struct {
	WorkspaceID   int64 `json:"workspace_id"`
	BankAccountID int64 `json:"bank_account_id"`
}

type WorkspaceInvite struct {
	ID          int64              `json:"id"`
	WorkspaceID int64              `json:"workspace_id"`
	Code        string             `json:"code"`
	Role        MemberRole         `json:"role"`
	CreatedBy   int64              `json:"created_by"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	UsedBy      pgtype.Int8        `json:"used_by"`
	UsedAt      pgtype.Timestamptz `json:"used_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type WorkspaceMember struct {
	WorkspaceID int64              `json:"workspace_id"`
	UserID      int64              `json:"user_id"`
	Role        MemberRole         `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
