// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BulkDeleteTransactions(ctx context.Context, arg BulkDeleteTransactionsParams) (pgconn.CommandTag, error)
	BulkUpdateFirstEntryCategory(ctx context.Context, arg BulkUpdateFirstEntryCategoryParams) (pgconn.CommandTag, error)
	DeleteBankConnection(ctx context.Context, arg DeleteBankConnectionParams) (pgconn.CommandTag, error)
	DeleteCategory(ctx context.Context, id int64) error
	DeleteEntriesByTransaction(ctx context.Context, transactionID int64) error
	DeleteFunding(ctx context.Context, arg DeleteFundingParams) (pgconn.CommandTag, error)
	DeleteMember(ctx context.Context, arg DeleteMemberParams) error
	DeleteRule(ctx context.Context, id int64) error
	DeleteTransaction(ctx context.Context, id int64) error
	DeleteWorkspace(ctx context.Context, id int64) error
	ExistsByFingerprint(ctx context.Context, arg ExistsByFingerprintParams) (bool, error)
	GetBankAccountByIBANAndCurrencyForUser(ctx context.Context, arg GetBankAccountByIBANAndCurrencyForUserParams) (BankAccount, error)
	GetBankAccountByID(ctx context.Context, id int64) (BankAccount, error)
	GetBankConnectionByID(ctx context.Context, id int64) (BankConnection, error)
	GetCategoryBudgetsByWorkspace(ctx context.Context, arg GetCategoryBudgetsByWorkspaceParams) ([]Funding, error)
	GetCategoryByID(ctx context.Context, id int64) (Category, error)
	GetCategoryByName(ctx context.Context, arg GetCategoryByNameParams) (Category, error)
	GetCategoryBySlug(ctx context.Context, arg GetCategoryBySlugParams) (Category, error)
	GetFundingsByWorkspaceAndUsers(ctx context.Context, arg GetFundingsByWorkspaceAndUsersParams) ([]Funding, error)
	GetInviteByCode(ctx context.Context, code string) (GetInviteByCodeRow, error)
	GetMember(ctx context.Context, arg GetMemberParams) (WorkspaceMember, error)
	GetOverallBudgetByWorkspace(ctx context.Context, arg GetOverallBudgetByWorkspaceParams) ([]Funding, error)
	GetRuleByID(ctx context.Context, id int64) (CategorizationRule, error)
	GetTransactionByID(ctx context.Context, id int64) (GetTransactionByIDRow, error)
	GetTransactionsByIDs(ctx context.Context, arg GetTransactionsByIDsParams) ([]GetTransactionsByIDsRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	GetWorkspaceByID(ctx context.Context, id int64) (Workspace, error)
	InsertBankAccount(ctx context.Context, arg InsertBankAccountParams) (BankAccount, error)
	InsertBankConnection(ctx context.Context, arg InsertBankConnectionParams) (BankConnection, error)
	InsertCategory(ctx context.Context, arg InsertCategoryParams) (Category, error)
	InsertEntry(ctx context.Context, arg InsertEntryParams) (Entry, error)
	InsertInvite(ctx context.Context, arg InsertInviteParams) (WorkspaceInvite, error)
	InsertMember(ctx context.Context, arg InsertMemberParams) (WorkspaceMember, error)
	InsertRule(ctx context.Context, arg InsertRuleParams) (CategorizationRule, error)
	InsertTransaction(ctx context.Context, arg InsertTransactionParams) (InsertTransactionRow, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error)
	InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) (Workspace, error)
	LinkBankAccountToWorkspace(ctx context.Context, arg LinkBankAccountToWorkspaceParams) error
	ListActiveBankConnections(ctx context.Context) ([]BankConnection, error)
	ListAllTransactionEntries(ctx context.Context, workspaceID int64) ([]ListAllTransactionEntriesRow, error)
	ListBankAccountsByConnection(ctx context.Context, bankConnectionID int64) ([]BankAccount, error)
	ListBankAccountsByUser(ctx context.Context, userID int64) ([]ListBankAccountsByUserRow, error)
	ListBankAccountsByWorkspace(ctx context.Context, workspaceID int64) ([]ListBankAccountsByWorkspaceRow, error)
	ListBankConnectionsByUser(ctx context.Context, userID int64) ([]BankConnection, error)
	ListCategoriesByWorkspace(ctx context.Context, workspaceID int64) ([]Category, error)
	ListEnabledRulesForResolution(ctx context.Context, arg ListEnabledRulesForResolutionParams) ([]CategorizationRule, error)
	ListEntriesByTransaction(ctx context.Context, transactionID int64) ([]Entry, error)
	ListEntriesByTransactionIDs(ctx context.Context, dollar_1 []int64) ([]Entry, error)
	ListFundingsByWorkspace(ctx context.Context, arg ListFundingsByWorkspaceParams) ([]Funding, error)
	ListMembers(ctx context.Context, workspaceID int64) ([]WorkspaceMember, error)
	ListMembersWithProfiles(ctx context.Context, workspaceID int64) ([]ListMembersWithProfilesRow, error)
	ListRulesByWorkspace(ctx context.Context, workspaceID pgtype.Int8) ([]CategorizationRule, error)
	ListTransactionsByWorkspace(ctx context.Context, arg ListTransactionsByWorkspaceParams) ([]ListTransactionsByWorkspaceRow, error)
	ListWorkspacesByBankAccount(ctx context.Context, bankAccountID int64) ([]int64, error)
	ListWorkspacesByUser(ctx context.Context, userID int64) ([]ListWorkspacesByUserRow, error)
	MarkInviteUsed(ctx context.Context, arg MarkInviteUsedParams) error
	RelinkOrphanedTransactions(ctx context.Context, arg RelinkOrphanedTransactionsParams) (pgconn.CommandTag, error)
	ToggleRuleEnabled(ctx context.Context, arg ToggleRuleEnabledParams) (CategorizationRule, error)
	UnlinkBankAccountFromWorkspace(ctx context.Context, arg UnlinkBankAccountFromWorkspaceParams) (pgconn.CommandTag, error)
	UpdateBankAccountConnection(ctx context.Context, arg UpdateBankAccountConnectionParams) error
	UpdateBankAccountCustomName(ctx context.Context, arg UpdateBankAccountCustomNameParams) (BankAccount, error)
	UpdateBankAccountLastSyncedAt(ctx context.Context, arg UpdateBankAccountLastSyncedAtParams) error
	UpdateBankConnectionSession(ctx context.Context, arg UpdateBankConnectionSessionParams) error
	UpdateBankConnectionStatus(ctx context.Context, arg UpdateBankConnectionStatusParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateEntryCategory(ctx context.Context, arg UpdateEntryCategoryParams) error
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error
	UpdatePreferredLanguage(ctx context.Context, arg UpdatePreferredLanguageParams) (UpdatePreferredLanguageRow, error)
	UpdateRule(ctx context.Context, arg UpdateRuleParams) (CategorizationRule, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (UpdateTransactionRow, error)
	UpdateUserProvider(ctx context.Context, arg UpdateUserProviderParams) (UpdateUserProviderRow, error)
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
	UpsertFunding(ctx context.Context, arg UpsertFundingParams) (Funding, error)
}

var _ Querier = (*Queries)(nil)
