// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rules.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRule = `-- name: DeleteRule :exec
DELETE FROM categorization_rules WHERE id = $1
`

func (q *Queries) DeleteRule(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRule, id)
	return err
}

const getRuleByID = `-- name: GetRuleByID :one
SELECT id, scope, owner_id, workspace_id, match_pattern, target_category_id, priority, enabled, created_at, updated_at, amount_min, amount_max, bank_account_id, counterparty_iban
FROM categorization_rules
WHERE id = $1
`

func (q *Queries) GetRuleByID(ctx context.Context, id int64) (CategorizationRule, error) {
	row := q.db.QueryRow(ctx, getRuleByID, id)
	var i CategorizationRule
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.OwnerID,
		&i.WorkspaceID,
		&i.MatchPattern,
		&i.TargetCategoryID,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AmountMin,
		&i.AmountMax,
		&i.BankAccountID,
		&i.CounterpartyIban,
	)
	return i, err
}

const insertRule = `-- name: InsertRule :one
INSERT INTO categorization_rules (scope, owner_id, workspace_id, match_pattern, target_category_id, priority, enabled, amount_min, amount_max, bank_account_id, counterparty_iban)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, scope, owner_id, workspace_id, match_pattern, target_category_id, priority, enabled, created_at, updated_at, amount_min, amount_max, bank_account_id, counterparty_iban
`

type InsertRuleParams struct {
	Scope            RuleScope      `json:"scope"`
	OwnerID          pgtype.Int8    `json:"owner_id"`
	WorkspaceID      pgtype.Int8    `json:"workspace_id"`
	MatchPattern     string         `json:"match_pattern"`
	TargetCategoryID int64          `json:"target_category_id"`
	Priority         int32          `json:"priority"`
	Enabled          bool           `json:"enabled"`
	AmountMin        pgtype.Numeric `json:"amount_min"`
	AmountMax        pgtype.Numeric `json:"amount_max"`
	BankAccountID    pgtype.Int8    `json:"bank_account_id"`
	CounterpartyIban pgtype.Text    `json:"counterparty_iban"`
}

func (q *Queries) InsertRule(ctx context.Context, arg InsertRuleParams) (CategorizationRule, error) {
	row := q.db.QueryRow(ctx, insertRule,
		arg.Scope,
		arg.OwnerID,
		arg.WorkspaceID,
		arg.MatchPattern,
		arg.TargetCategoryID,
		arg.Priority,
		arg.Enabled,
		arg.AmountMin,
		arg.AmountMax,
		arg.BankAccountID,
		arg.CounterpartyIban,
	)
	var i CategorizationRule
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.OwnerID,
		&i.WorkspaceID,
		&i.MatchPattern,
		&i.TargetCategoryID,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AmountMin,
		&i.AmountMax,
		&i.BankAccountID,
		&i.CounterpartyIban,
	)
	return i, err
}

const listEnabledRulesForResolution = `-- name: ListEnabledRulesForResolution :many
SELECT id, scope, owner_id, workspace_id, match_pattern, target_category_id, priority, enabled, created_at, updated_at, amount_min, amount_max, bank_account_id, counterparty_iban
FROM categorization_rules
WHERE (workspace_id = $1 OR owner_id = $2 OR scope = 'system')
  AND enabled = true
ORDER BY
  CASE scope WHEN 'workspace' THEN 3 WHEN 'user' THEN 2 WHEN 'system' THEN 1 ELSE 0 END DESC,
  priority DESC
`

type ListEnabledRulesForResolutionParams struct {
	WorkspaceID pgtype.Int8 `json:"workspace_id"`
	OwnerID     pgtype.Int8 `json:"owner_id"`
}

func (q *Queries) ListEnabledRulesForResolution(ctx context.Context, arg ListEnabledRulesForResolutionParams) ([]CategorizationRule, error) {
	rows, err := q.db.Query(ctx, listEnabledRulesForResolution, arg.WorkspaceID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategorizationRule{}
	for rows.Next() {
		var i CategorizationRule
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.OwnerID,
			&i.WorkspaceID,
			&i.MatchPattern,
			&i.TargetCategoryID,
			&i.Priority,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AmountMin,
			&i.AmountMax,
			&i.BankAccountID,
			&i.CounterpartyIban,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRulesByWorkspace = `-- name: ListRulesByWorkspace :many
SELECT id, scope, owner_id, workspace_id, match_pattern, target_category_id, priority, enabled, created_at, updated_at, amount_min, amount_max, bank_account_id, counterparty_iban
FROM categorization_rules
WHERE workspace_id = $1
ORDER BY priority DESC
`

func (q *Queries) ListRulesByWorkspace(ctx context.Context, workspaceID pgtype.Int8) ([]CategorizationRule, error) {
	rows, err := q.db.Query(ctx, listRulesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategorizationRule{}
	for rows.Next() {
		var i CategorizationRule
		if err := rows.Scan(
			&i.ID,
			&i.Scope,
			&i.OwnerID,
			&i.WorkspaceID,
			&i.MatchPattern,
			&i.TargetCategoryID,
			&i.Priority,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AmountMin,
			&i.AmountMax,
			&i.BankAccountID,
			&i.CounterpartyIban,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleRuleEnabled = `-- name: ToggleRuleEnabled :one
UPDATE categorization_rules
SET enabled = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, scope, owner_id, workspace_id, match_pattern, target_category_id, priority, enabled, created_at, updated_at, amount_min, amount_max, bank_account_id, counterparty_iban
`

type ToggleRuleEnabledParams struct {
	ID      int64 `json:"id"`
	Enabled bool  `json:"enabled"`
}

func (q *Queries) ToggleRuleEnabled(ctx context.Context, arg ToggleRuleEnabledParams) (CategorizationRule, error) {
	row := q.db.QueryRow(ctx, toggleRuleEnabled, arg.ID, arg.Enabled)
	var i CategorizationRule
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.OwnerID,
		&i.WorkspaceID,
		&i.MatchPattern,
		&i.TargetCategoryID,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AmountMin,
		&i.AmountMax,
		&i.BankAccountID,
		&i.CounterpartyIban,
	)
	return i, err
}

const updateRule = `-- name: UpdateRule :one
UPDATE categorization_rules
SET match_pattern = $2, target_category_id = $3, priority = $4, amount_min = $5, amount_max = $6, bank_account_id = $7, counterparty_iban = $8, updated_at = NOW()
WHERE id = $1
RETURNING id, scope, owner_id, workspace_id, match_pattern, target_category_id, priority, enabled, created_at, updated_at, amount_min, amount_max, bank_account_id, counterparty_iban
`

type UpdateRuleParams struct {
	ID               int64          `json:"id"`
	MatchPattern     string         `json:"match_pattern"`
	TargetCategoryID int64          `json:"target_category_id"`
	Priority         int32          `json:"priority"`
	AmountMin        pgtype.Numeric `json:"amount_min"`
	AmountMax        pgtype.Numeric `json:"amount_max"`
	BankAccountID    pgtype.Int8    `json:"bank_account_id"`
	CounterpartyIban pgtype.Text    `json:"counterparty_iban"`
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) (CategorizationRule, error) {
	row := q.db.QueryRow(ctx, updateRule,
		arg.ID,
		arg.MatchPattern,
		arg.TargetCategoryID,
		arg.Priority,
		arg.AmountMin,
		arg.AmountMax,
		arg.BankAccountID,
		arg.CounterpartyIban,
	)
	var i CategorizationRule
	err := row.Scan(
		&i.ID,
		&i.Scope,
		&i.OwnerID,
		&i.WorkspaceID,
		&i.MatchPattern,
		&i.TargetCategoryID,
		&i.Priority,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AmountMin,
		&i.AmountMax,
		&i.BankAccountID,
		&i.CounterpartyIban,
	)
	return i, err
}
