// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const bulkDeleteTransactions = `-- name: BulkDeleteTransactions :execresult
DELETE FROM transactions
WHERE workspace_id = $1 AND id = ANY($2::bigint[])
`

type BulkDeleteTransactionsParams struct {
	WorkspaceID int64   `json:"workspace_id"`
	Column2     []int64 `json:"column_2"`
}

func (q *Queries) BulkDeleteTransactions(ctx context.Context, arg BulkDeleteTransactionsParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, bulkDeleteTransactions, arg.WorkspaceID, arg.Column2)
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTransaction, id)
	return err
}

const existsByFingerprint = `-- name: ExistsByFingerprint :one
SELECT EXISTS (
    SELECT 1 FROM transactions
    WHERE workspace_id = $1 AND fingerprint = $2
) AS exists
`

type ExistsByFingerprintParams struct {
	WorkspaceID int64       `json:"workspace_id"`
	Fingerprint pgtype.Text `json:"fingerprint"`
}

func (q *Queries) ExistsByFingerprint(ctx context.Context, arg ExistsByFingerprintParams) (bool, error) {
	row := q.db.QueryRow(ctx, existsByFingerprint, arg.WorkspaceID, arg.Fingerprint)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, workspace_id, created_by, total_amount, currency, description, date, fingerprint, source, transaction_type, notes, bank_account_id, iban, counterparty_iban, created_at, updated_at
FROM transactions
WHERE id = $1
`

type GetTransactionByIDRow struct {
	ID               int64              `json:"id"`
	WorkspaceID      int64              `json:"workspace_id"`
	CreatedBy        int64              `json:"created_by"`
	TotalAmount      pgtype.Numeric     `json:"total_amount"`
	Currency         string             `json:"currency"`
	Description      string             `json:"description"`
	Date             pgtype.Date        `json:"date"`
	Fingerprint      pgtype.Text        `json:"fingerprint"`
	Source           TransactionSource  `json:"source"`
	TransactionType  TransactionType    `json:"transaction_type"`
	Notes            string             `json:"notes"`
	BankAccountID    pgtype.Int8        `json:"bank_account_id"`
	Iban             pgtype.Text        `json:"iban"`
	CounterpartyIban pgtype.Text        `json:"counterparty_iban"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, id int64) (GetTransactionByIDRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.TotalAmount,
		&i.Currency,
		&i.Description,
		&i.Date,
		&i.Fingerprint,
		&i.Source,
		&i.TransactionType,
		&i.Notes,
		&i.BankAccountID,
		&i.Iban,
		&i.CounterpartyIban,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionsByIDs = `-- name: GetTransactionsByIDs :many
SELECT id, workspace_id, created_by, total_amount, currency, description, date, fingerprint, source, transaction_type, notes, bank_account_id, iban, counterparty_iban, created_at, updated_at
FROM transactions
WHERE workspace_id = $1 AND id = ANY($2::bigint[])
`

type GetTransactionsByIDsParams struct {
	WorkspaceID int64   `json:"workspace_id"`
	Column2     []int64 `json:"column_2"`
}

type GetTransactionsByIDsRow struct {
	ID               int64              `json:"id"`
	WorkspaceID      int64              `json:"workspace_id"`
	CreatedBy        int64              `json:"created_by"`
	TotalAmount      pgtype.Numeric     `json:"total_amount"`
	Currency         string             `json:"currency"`
	Description      string             `json:"description"`
	Date             pgtype.Date        `json:"date"`
	Fingerprint      pgtype.Text        `json:"fingerprint"`
	Source           TransactionSource  `json:"source"`
	TransactionType  TransactionType    `json:"transaction_type"`
	Notes            string             `json:"notes"`
	BankAccountID    pgtype.Int8        `json:"bank_account_id"`
	Iban             pgtype.Text        `json:"iban"`
	CounterpartyIban pgtype.Text        `json:"counterparty_iban"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTransactionsByIDs(ctx context.Context, arg GetTransactionsByIDsParams) ([]GetTransactionsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsByIDs, arg.WorkspaceID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTransactionsByIDsRow{}
	for rows.Next() {
		var i GetTransactionsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CreatedBy,
			&i.TotalAmount,
			&i.Currency,
			&i.Description,
			&i.Date,
			&i.Fingerprint,
			&i.Source,
			&i.TransactionType,
			&i.Notes,
			&i.BankAccountID,
			&i.Iban,
			&i.CounterpartyIban,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTransaction = `-- name: InsertTransaction :one
INSERT INTO transactions (workspace_id, created_by, total_amount, currency, description, date, fingerprint, source, transaction_type, notes, bank_account_id, iban, counterparty_iban)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, workspace_id, created_by, total_amount, currency, description, date, fingerprint, source, transaction_type, notes, bank_account_id, iban, counterparty_iban, created_at, updated_at
`

type InsertTransactionParams struct {
	WorkspaceID      int64             `json:"workspace_id"`
	CreatedBy        int64             `json:"created_by"`
	TotalAmount      pgtype.Numeric    `json:"total_amount"`
	Currency         string            `json:"currency"`
	Description      string            `json:"description"`
	Date             pgtype.Date       `json:"date"`
	Fingerprint      pgtype.Text       `json:"fingerprint"`
	Source           TransactionSource `json:"source"`
	TransactionType  TransactionType   `json:"transaction_type"`
	Notes            string            `json:"notes"`
	BankAccountID    pgtype.Int8       `json:"bank_account_id"`
	Iban             pgtype.Text       `json:"iban"`
	CounterpartyIban pgtype.Text       `json:"counterparty_iban"`
}

type InsertTransactionRow struct {
	ID               int64              `json:"id"`
	WorkspaceID      int64              `json:"workspace_id"`
	CreatedBy        int64              `json:"created_by"`
	TotalAmount      pgtype.Numeric     `json:"total_amount"`
	Currency         string             `json:"currency"`
	Description      string             `json:"description"`
	Date             pgtype.Date        `json:"date"`
	Fingerprint      pgtype.Text        `json:"fingerprint"`
	Source           TransactionSource  `json:"source"`
	TransactionType  TransactionType    `json:"transaction_type"`
	Notes            string             `json:"notes"`
	BankAccountID    pgtype.Int8        `json:"bank_account_id"`
	Iban             pgtype.Text        `json:"iban"`
	CounterpartyIban pgtype.Text        `json:"counterparty_iban"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertTransaction(ctx context.Context, arg InsertTransactionParams) (InsertTransactionRow, error) {
	row := q.db.QueryRow(ctx, insertTransaction,
		arg.WorkspaceID,
		arg.CreatedBy,
		arg.TotalAmount,
		arg.Currency,
		arg.Description,
		arg.Date,
		arg.Fingerprint,
		arg.Source,
		arg.TransactionType,
		arg.Notes,
		arg.BankAccountID,
		arg.Iban,
		arg.CounterpartyIban,
	)
	var i InsertTransactionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.TotalAmount,
		&i.Currency,
		&i.Description,
		&i.Date,
		&i.Fingerprint,
		&i.Source,
		&i.TransactionType,
		&i.Notes,
		&i.BankAccountID,
		&i.Iban,
		&i.CounterpartyIban,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllTransactionEntries = `-- name: ListAllTransactionEntries :many
SELECT t.id, t.description, t.created_by, e.id AS entry_id, e.category_id, t.transaction_type, t.total_amount, t.bank_account_id, t.counterparty_iban
FROM transactions t
JOIN entries e ON e.transaction_id = t.id
WHERE t.workspace_id = $1
ORDER BY t.id
`

type ListAllTransactionEntriesRow struct {
	ID               int64           `json:"id"`
	Description      string          `json:"description"`
	CreatedBy        int64           `json:"created_by"`
	EntryID          int64           `json:"entry_id"`
	CategoryID       int64           `json:"category_id"`
	TransactionType  TransactionType `json:"transaction_type"`
	TotalAmount      pgtype.Numeric  `json:"total_amount"`
	BankAccountID    pgtype.Int8     `json:"bank_account_id"`
	CounterpartyIban pgtype.Text     `json:"counterparty_iban"`
}

func (q *Queries) ListAllTransactionEntries(ctx context.Context, workspaceID int64) ([]ListAllTransactionEntriesRow, error) {
	rows, err := q.db.Query(ctx, listAllTransactionEntries, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllTransactionEntriesRow{}
	for rows.Next() {
		var i ListAllTransactionEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.CreatedBy,
			&i.EntryID,
			&i.CategoryID,
			&i.TransactionType,
			&i.TotalAmount,
			&i.BankAccountID,
			&i.CounterpartyIban,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByWorkspace = `-- name: ListTransactionsByWorkspace :many
SELECT t.id, t.workspace_id, t.created_by, t.total_amount, t.currency, t.description, t.date, t.fingerprint, t.source, t.transaction_type, t.notes, t.bank_account_id, t.iban, t.counterparty_iban, t.created_at, t.updated_at,
       COALESCE(bc.institution_name, '') AS bank_name
FROM transactions t
LEFT JOIN bank_accounts ba ON ba.id = t.bank_account_id
LEFT JOIN bank_connections bc ON bc.id = ba.bank_connection_id
WHERE t.workspace_id = $1 AND t.date >= $2 AND t.date < $3
  AND ($6::transaction_type IS NULL OR t.transaction_type = $6)
  AND ($7::text IS NULL OR t.currency = $7)
  AND ($8::bigint IS NULL OR EXISTS (
    SELECT 1 FROM entries e WHERE e.transaction_id = t.id AND e.category_id = $8
  ))
  AND ($9::bigint IS NULL OR t.bank_account_id = $9)
  AND ($10::numeric IS NULL OR ABS(t.total_amount) >= $10)
  AND ($11::numeric IS NULL OR ABS(t.total_amount) <= $11)
ORDER BY t.date DESC, t.id DESC
LIMIT $4 OFFSET $5
`

type ListTransactionsByWorkspaceParams struct {
	WorkspaceID     int64               `json:"workspace_id"`
	Date            pgtype.Date         `json:"date"`
	Date_2          pgtype.Date         `json:"date_2"`
	Limit           int32               `json:"limit"`
	Offset          int32               `json:"offset"`
	TransactionType NullTransactionType `json:"transaction_type"`
	Currency        pgtype.Text         `json:"currency"`
	CategoryID      pgtype.Int8         `json:"category_id"`
	BankAccountID   pgtype.Int8         `json:"bank_account_id"`
	AmountMin       pgtype.Numeric      `json:"amount_min"`
	AmountMax       pgtype.Numeric      `json:"amount_max"`
}

type ListTransactionsByWorkspaceRow struct {
	ID               int64              `json:"id"`
	WorkspaceID      int64              `json:"workspace_id"`
	CreatedBy        int64              `json:"created_by"`
	TotalAmount      pgtype.Numeric     `json:"total_amount"`
	Currency         string             `json:"currency"`
	Description      string             `json:"description"`
	Date             pgtype.Date        `json:"date"`
	Fingerprint      pgtype.Text        `json:"fingerprint"`
	Source           TransactionSource  `json:"source"`
	TransactionType  TransactionType    `json:"transaction_type"`
	Notes            string             `json:"notes"`
	BankAccountID    pgtype.Int8        `json:"bank_account_id"`
	Iban             pgtype.Text        `json:"iban"`
	CounterpartyIban pgtype.Text        `json:"counterparty_iban"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	BankName         string             `json:"bank_name"`
}

func (q *Queries) ListTransactionsByWorkspace(ctx context.Context, arg ListTransactionsByWorkspaceParams) ([]ListTransactionsByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByWorkspace,
		arg.WorkspaceID,
		arg.Date,
		arg.Date_2,
		arg.Limit,
		arg.Offset,
		arg.TransactionType,
		arg.Currency,
		arg.CategoryID,
		arg.BankAccountID,
		arg.AmountMin,
		arg.AmountMax,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsByWorkspaceRow{}
	for rows.Next() {
		var i ListTransactionsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CreatedBy,
			&i.TotalAmount,
			&i.Currency,
			&i.Description,
			&i.Date,
			&i.Fingerprint,
			&i.Source,
			&i.TransactionType,
			&i.Notes,
			&i.BankAccountID,
			&i.Iban,
			&i.CounterpartyIban,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BankName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const relinkOrphanedTransactions = `-- name: RelinkOrphanedTransactions :execresult
UPDATE transactions
SET bank_account_id = $1, updated_at = NOW()
WHERE iban = $2 AND currency = $3 AND bank_account_id IS NULL AND workspace_id = $4
`

type RelinkOrphanedTransactionsParams struct {
	BankAccountID pgtype.Int8 `json:"bank_account_id"`
	Iban          pgtype.Text `json:"iban"`
	Currency      string      `json:"currency"`
	WorkspaceID   int64       `json:"workspace_id"`
}

func (q *Queries) RelinkOrphanedTransactions(ctx context.Context, arg RelinkOrphanedTransactionsParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, relinkOrphanedTransactions,
		arg.BankAccountID,
		arg.Iban,
		arg.Currency,
		arg.WorkspaceID,
	)
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET description = $2, date = $3, transaction_type = $4, notes = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, workspace_id, created_by, total_amount, currency, description, date, fingerprint, source, transaction_type, notes, bank_account_id, iban, counterparty_iban, created_at, updated_at
`

type UpdateTransactionParams struct {
	ID              int64           `json:"id"`
	Description     string          `json:"description"`
	Date            pgtype.Date     `json:"date"`
	TransactionType TransactionType `json:"transaction_type"`
	Notes           string          `json:"notes"`
}

type UpdateTransactionRow struct {
	ID               int64              `json:"id"`
	WorkspaceID      int64              `json:"workspace_id"`
	CreatedBy        int64              `json:"created_by"`
	TotalAmount      pgtype.Numeric     `json:"total_amount"`
	Currency         string             `json:"currency"`
	Description      string             `json:"description"`
	Date             pgtype.Date        `json:"date"`
	Fingerprint      pgtype.Text        `json:"fingerprint"`
	Source           TransactionSource  `json:"source"`
	TransactionType  TransactionType    `json:"transaction_type"`
	Notes            string             `json:"notes"`
	BankAccountID    pgtype.Int8        `json:"bank_account_id"`
	Iban             pgtype.Text        `json:"iban"`
	CounterpartyIban pgtype.Text        `json:"counterparty_iban"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (UpdateTransactionRow, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.Description,
		arg.Date,
		arg.TransactionType,
		arg.Notes,
	)
	var i UpdateTransactionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.TotalAmount,
		&i.Currency,
		&i.Description,
		&i.Date,
		&i.Fingerprint,
		&i.Source,
		&i.TransactionType,
		&i.Notes,
		&i.BankAccountID,
		&i.Iban,
		&i.CounterpartyIban,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
