// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, avatar_url, provider, provider_id, preferred_language, created_at, updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID                int64              `json:"id"`
	Email             string             `json:"email"`
	DisplayName       string             `json:"display_name"`
	AvatarUrl         string             `json:"avatar_url"`
	Provider          AuthProvider       `json:"provider"`
	ProviderID        string             `json:"provider_id"`
	PreferredLanguage string             `json:"preferred_language"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderID,
		&i.PreferredLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, avatar_url, provider, provider_id, preferred_language, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID                int64              `json:"id"`
	Email             string             `json:"email"`
	DisplayName       string             `json:"display_name"`
	AvatarUrl         string             `json:"avatar_url"`
	Provider          AuthProvider       `json:"provider"`
	ProviderID        string             `json:"provider_id"`
	PreferredLanguage string             `json:"preferred_language"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderID,
		&i.PreferredLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (email, display_name, avatar_url, provider, provider_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, display_name, avatar_url, provider, provider_id, preferred_language, created_at, updated_at
`

type InsertUserParams struct {
	Email       string       `json:"email"`
	DisplayName string       `json:"display_name"`
	AvatarUrl   string       `json:"avatar_url"`
	Provider    AuthProvider `json:"provider"`
	ProviderID  string       `json:"provider_id"`
}

type InsertUserRow struct {
	ID                int64              `json:"id"`
	Email             string             `json:"email"`
	DisplayName       string             `json:"display_name"`
	AvatarUrl         string             `json:"avatar_url"`
	Provider          AuthProvider       `json:"provider"`
	ProviderID        string             `json:"provider_id"`
	PreferredLanguage string             `json:"preferred_language"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Provider,
		arg.ProviderID,
	)
	var i InsertUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderID,
		&i.PreferredLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePreferredLanguage = `-- name: UpdatePreferredLanguage :one
UPDATE users
SET preferred_language = $2,
    updated_at         = NOW()
WHERE id = $1
RETURNING id, email, display_name, avatar_url, provider, provider_id, preferred_language, created_at, updated_at
`

type UpdatePreferredLanguageParams struct {
	ID                int64  `json:"id"`
	PreferredLanguage string `json:"preferred_language"`
}

type UpdatePreferredLanguageRow struct {
	ID                int64              `json:"id"`
	Email             string             `json:"email"`
	DisplayName       string             `json:"display_name"`
	AvatarUrl         string             `json:"avatar_url"`
	Provider          AuthProvider       `json:"provider"`
	ProviderID        string             `json:"provider_id"`
	PreferredLanguage string             `json:"preferred_language"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePreferredLanguage(ctx context.Context, arg UpdatePreferredLanguageParams) (UpdatePreferredLanguageRow, error) {
	row := q.db.QueryRow(ctx, updatePreferredLanguage, arg.ID, arg.PreferredLanguage)
	var i UpdatePreferredLanguageRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderID,
		&i.PreferredLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProvider = `-- name: UpdateUserProvider :one
UPDATE users
SET display_name = $2,
    avatar_url   = $3,
    provider     = $4,
    provider_id  = $5,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, email, display_name, avatar_url, provider, provider_id, preferred_language, created_at, updated_at
`

type UpdateUserProviderParams struct {
	ID          int64        `json:"id"`
	DisplayName string       `json:"display_name"`
	AvatarUrl   string       `json:"avatar_url"`
	Provider    AuthProvider `json:"provider"`
	ProviderID  string       `json:"provider_id"`
}

type UpdateUserProviderRow struct {
	ID                int64              `json:"id"`
	Email             string             `json:"email"`
	DisplayName       string             `json:"display_name"`
	AvatarUrl         string             `json:"avatar_url"`
	Provider          AuthProvider       `json:"provider"`
	ProviderID        string             `json:"provider_id"`
	PreferredLanguage string             `json:"preferred_language"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserProvider(ctx context.Context, arg UpdateUserProviderParams) (UpdateUserProviderRow, error) {
	row := q.db.QueryRow(ctx, updateUserProvider,
		arg.ID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Provider,
		arg.ProviderID,
	)
	var i UpdateUserProviderRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderID,
		&i.PreferredLanguage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
