// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type DeleteMemberParams struct {
	WorkspaceID int64 `json:"workspace_id"`
	UserID      int64 `json:"user_id"`
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) error {
	_, err := q.db.Exec(ctx, deleteMember, arg.WorkspaceID, arg.UserID)
	return err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteWorkspace, id)
	return err
}

const getMember = `-- name: GetMember :one
SELECT workspace_id, user_id, role, created_at
FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type GetMemberParams struct {
	WorkspaceID int64 `json:"workspace_id"`
	UserID      int64 `json:"user_id"`
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getMember, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, name, description, owner_id, created_at, updated_at
FROM workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id int64) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMember = `-- name: InsertMember :one
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING workspace_id, user_id, role, created_at
`

type InsertMemberParams struct {
	WorkspaceID int64      `json:"workspace_id"`
	UserID      int64      `json:"user_id"`
	Role        MemberRole `json:"role"`
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, insertMember, arg.WorkspaceID, arg.UserID, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const insertWorkspace = `-- name: InsertWorkspace :one
INSERT INTO workspaces (name, description, owner_id)
VALUES ($1, $2, $3)
RETURNING id, name, description, owner_id, created_at, updated_at
`

type InsertWorkspaceParams struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	OwnerID     int64  `json:"owner_id"`
}

func (q *Queries) InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, insertWorkspace, arg.Name, arg.Description, arg.OwnerID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT workspace_id, user_id, role, created_at
FROM workspace_members
WHERE workspace_id = $1
ORDER BY created_at
`

func (q *Queries) ListMembers(ctx context.Context, workspaceID int64) ([]WorkspaceMember, error) {
	rows, err := q.db.Query(ctx, listMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceMember{}
	for rows.Next() {
		var i WorkspaceMember
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembersWithProfiles = `-- name: ListMembersWithProfiles :many
SELECT wm.workspace_id, wm.user_id, wm.role, wm.created_at,
       u.display_name, u.email, u.avatar_url
FROM workspace_members wm
JOIN users u ON u.id = wm.user_id
WHERE wm.workspace_id = $1
ORDER BY wm.created_at
`

type ListMembersWithProfilesRow struct {
	WorkspaceID int64              `json:"workspace_id"`
	UserID      int64              `json:"user_id"`
	Role        MemberRole         `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DisplayName string             `json:"display_name"`
	Email       string             `json:"email"`
	AvatarUrl   string             `json:"avatar_url"`
}

func (q *Queries) ListMembersWithProfiles(ctx context.Context, workspaceID int64) ([]ListMembersWithProfilesRow, error) {
	rows, err := q.db.Query(ctx, listMembersWithProfiles, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersWithProfilesRow{}
	for rows.Next() {
		var i ListMembersWithProfilesRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.DisplayName,
			&i.Email,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByUser = `-- name: ListWorkspacesByUser :many
SELECT w.id, w.name, w.description, w.owner_id, w.created_at, w.updated_at,
       (SELECT COUNT(*) FROM workspace_members wm2 WHERE wm2.workspace_id = w.id)::bigint AS member_count
FROM workspaces w
JOIN workspace_members wm ON w.id = wm.workspace_id
WHERE wm.user_id = $1
ORDER BY w.created_at DESC
`

type ListWorkspacesByUserRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	OwnerID     int64              `json:"owner_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	MemberCount int64              `json:"member_count"`
}

func (q *Queries) ListWorkspacesByUser(ctx context.Context, userID int64) ([]ListWorkspacesByUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesByUserRow{}
	for rows.Next() {
		var i ListWorkspacesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberRole = `-- name: UpdateMemberRole :exec
UPDATE workspace_members
SET role = $3
WHERE workspace_id = $1 AND user_id = $2
`

type UpdateMemberRoleParams struct {
	WorkspaceID int64      `json:"workspace_id"`
	UserID      int64      `json:"user_id"`
	Role        MemberRole `json:"role"`
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateMemberRole, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
SET name        = $2,
    description = $3,
    updated_at  = NOW()
WHERE id = $1
RETURNING id, name, description, owner_id, created_at, updated_at
`

type UpdateWorkspaceParams struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace, arg.ID, arg.Name, arg.Description)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
